### PR TITLE
Temperature PHY variable change

### PR DESCRIPTION
**Pull request by pax0707**
UniFI changed local temperature variable from PHY to Local

[21:12:09]   "temperatures": [
[21:12:09]     {
[21:12:09]       "name": "Local",
[21:12:09]       "type": "board",
[21:12:09]       "value": 69
[21:12:09]     },
[21:12:09]     {
[21:12:09]       "name": "CPU",
[21:12:09]       "type": "cpu",
[21:12:09]       "value": 81.875
[21:12:09]     }

### CODE REVIEW

**Comment by patricegautier** [comment]
hi @pax0707 

I see both come back from my UDMP (on v2.4.26)

  "temperatures": [
    {
      "name": "CPU",
      "type": "cpu",
      "value": 59
    },
    {
      "name": "Local",
      "type": "board",
      "value": 42.25
    },
    {
      "name": "PHY",
      "type": "board",
      "value": 41.75
    }
  ],


Which version are you on?

As far as I can see the PHY temp has not gone away:

image

**Comment by pax0707** [comment]
I got the base one, also on 2.4.26.
Does the pro one have an extra sensor?

For the base, it looks like Local = temp1, CPU = temp2.

```
Model:       UniFi Dream Machine
Version:     2.4.26.7228

```
```
  "temperatures": [
    {
      "name": "Local",
      "type": "board",
      "value": 69
    },
    {
      "name": "CPU",
      "type": "cpu",
      "value": 82.25
    }
  ],
```

```
root@Overmind:~# sensors
lm63-i2c-0-4c
Adapter: Synopsys DesignWare I2C adapter
fan1:        2265 RPM  (min = 1748 RPM)
temp1:        +69.0°C  (high = +70.0°C)
temp2:        +82.2°C  (low  =  +0.0°C, high = +94.0°C)
                       (crit = +93.0°C, hyst = +83.0°C)
```

**Comment by patricegautier** [comment]
BTW I believe this one was taken care off by one of the commits right after you submitted this.. Can you confirm?

**Comment by pax0707** [comment]
Looks good now.

**Pull request closed without merging**
